const slides=[...document.querySelectorAll('.slide')],dots=[...document.querySelectorAll('.dot')];
const title=document.querySelector('#hero-title'),text=document.querySelector('#hero-text'),eyebrow=document.querySelector('#hero-eyebrow');
let current=0,timer;
function showSlide(index){current=index;slides.forEach((s,i)=>s.classList.toggle('active',i===index));dots.forEach((d,i)=>{const active=i===index;d.classList.toggle('active',active);d.setAttribute('aria-current',active?'true':'false')});const s=slides[index];title.textContent=s.dataset.title;text.textContent=s.dataset.text;eyebrow.textContent=s.dataset.eyebrow;clearInterval(timer);timer=setInterval(()=>showSlide((current+1)%slides.length),10000)}
dots.forEach((d,i)=>d.addEventListener('click',()=>showSlide(i)));showSlide(0);
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('.nav-menu');toggle.addEventListener('click',()=>{nav.classList.toggle('open');toggle.setAttribute('aria-expanded',nav.classList.contains('open'))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const lightbox=document.querySelector('.lightbox'),lightImg=lightbox.querySelector('img');document.querySelectorAll('.gallery-item img').forEach(img=>img.addEventListener('click',()=>{lightImg.src=img.src;lightImg.alt=img.alt;lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false')}));function closeLightbox(){lightbox.classList.remove('open');lightbox.setAttribute('aria-hidden','true')}lightbox.querySelector('button').addEventListener('click',closeLightbox);lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeLightbox()});
document.querySelector('.contact-form').addEventListener('submit',e=>{e.preventDefault();alert('Interesse registrado! Conecte este formulário ao WhatsApp ou serviço de e-mail na publicação.');});
